# Generated by Django 3.0.2 on 2021-03-31 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0003_auto_20210331_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditem',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
