# Generated by Django 3.0.2 on 2021-03-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0004_userfooditem_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='created_date',
        ),
    ]
