# Generated by Django 3.0.2 on 2021-03-31 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0005_remove_userfooditem_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditem',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
