# Generated by Django 3.0.2 on 2021-03-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0006_userfooditem_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='post_date',
        ),
    ]
