# Generated by Django 3.0.2 on 2021-03-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0007_remove_userfooditem_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calorie.Customer'),
        ),
    ]
