# Generated by Django 3.0.2 on 2021-04-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0008_auto_20210331_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfooditem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calorie.Customer'),
        ),
    ]
