# Generated by Django 3.0.2 on 2021-04-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0009_auto_20210401_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='fooditem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calorie.Fooditem'),
        ),
    ]
