# Generated by Django 3.0.2 on 2021-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0010_auto_20210401_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='fooditem',
            field=models.ManyToManyField(to='Calorie.Fooditem'),
        ),
    ]
