# Generated by Django 3.0.2 on 2021-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0012_auto_20210405_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='fooditem',
            field=models.ManyToManyField(to='Calorie.Fooditem'),
        ),
    ]
